# Generated by Django 3.0.8 on 2020-07-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(blank=True, max_length=30)),
                ('date_to', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
